name = "nextbridge-pw-gateway"
main = "worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "fbff1b065e8e9cb5e26b8110a734597c"

[vars]
ENVIRONMENT = "production"
